// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: create_feed_follow.sql

package database

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const createFeedFollow = `-- name: CreateFeedFollow :one
WITH insert_feed_follows AS(
    INSERT INTO feed_follows (id,created_at,updated_at,user_id,feed_id)
    VALUES (
        $1,
        $2,
        $3,
        $4,
        $5
    )
RETURNING id, created_at, updated_at, user_id, feed_id, last_fetched_at
)
SELECT 
    insert_feed_follows.id, insert_feed_follows.created_at, insert_feed_follows.updated_at, insert_feed_follows.user_id, insert_feed_follows.feed_id, insert_feed_follows.last_fetched_at,
    users.name AS user_name, 
    feeds.name AS feed_name
FROM
    insert_feed_follows
INNER JOIN
    users ON users.id = insert_feed_follows.user_id
INNER JOIN
    feeds ON feeds.id = insert_feed_follows.feed_id
`

type CreateFeedFollowParams struct {
	ID        uuid.UUID
	CreatedAt time.Time
	UpdatedAt time.Time
	UserID    uuid.UUID
	FeedID    uuid.UUID
}

type CreateFeedFollowRow struct {
	ID            uuid.UUID
	CreatedAt     time.Time
	UpdatedAt     time.Time
	UserID        uuid.UUID
	FeedID        uuid.UUID
	LastFetchedAt sql.NullTime
	UserName      string
	FeedName      string
}

func (q *Queries) CreateFeedFollow(ctx context.Context, arg CreateFeedFollowParams) (CreateFeedFollowRow, error) {
	row := q.db.QueryRowContext(ctx, createFeedFollow,
		arg.ID,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.UserID,
		arg.FeedID,
	)
	var i CreateFeedFollowRow
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserID,
		&i.FeedID,
		&i.LastFetchedAt,
		&i.UserName,
		&i.FeedName,
	)
	return i, err
}
