-- +goose Up
ALTER TABLE posts 
    ALTER COLUMN title TYPE TEXT,
    ALTER COLUMN url TYPE TEXT,
    ALTER COLUMN description TYPE TEXT;

ALTER TABLE feeds 
    ALTER COLUMN name TYPE TEXT,
    ALTER COLUMN url TYPE TEXT;

ALTER TABLE users 
    ALTER COLUMN name TYPE TEXT;

-- +goose Down
ALTER TABLE posts 
    ALTER COLUMN title TYPE VARCHAR(100),
    ALTER COLUMN url TYPE VARCHAR(200),
    ALTER COLUMN description TYPE VARCHAR(200);

ALTER TABLE feeds 
    ALTER COLUMN name TYPE VARCHAR(100),
    ALTER COLUMN url TYPE VARCHAR(200);

ALTER TABLE users 
    ALTER COLUMN name TYPE VARCHAR(100);